tap "mongodb/brew"


cask "iterm2"

# 🛠️ Outils essentiels
brew "git"
brew "starship"
cask "orbstack"
brew "postgresql"
brew "kubectl"
brew "helm"
brew "derailed/k9s/k9s"
brew "kubectx"
brew "dnsmasq"
brew "mysql"
brew "mongodb-community@8.0"
brew "docker-compose"

# 📦 Apps Mac (GUI)
cast "gather"
cask "google-chrome"
cask "microsoft-teams"
cask "visual-studio-code"
cask "insomnia"
cask "chatgpt"
cask "sequel-ace"
cask "slack"
cask "raycast"
cask "notion"
cask "fork"
cask "gitbutler"
cask "bbedit"
cask "obsidian"
cask "mongodb-compass"